#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Export the Claude Code agent definitions to platform-neutral prompt files.

Other coding agents — Codex, Cursor, Zed, Aider, Continue — read `AGENTS.md` and
plain prompt files, not `.claude/agents/*.md` with its YAML frontmatter. This
makes the definitions usable there.

**It also refuses to pretend the port is equivalent, and that is the point.**

The owner-facing agent's safety property is not its prose. It is the line
`tools: Read, Grep, Glob` in the Claude frontmatter, which removes the ability
to search literature at all. That mechanism was adopted *after* the same
restriction, written as prose, failed twice on the same test question — once as
a section, once as a rule declared to outrank every other rule in the file. Both
times the agent searched PubMed live and answered a condition the knowledge base
does not cover.

So each exported prompt carries a header stating what the host platform must
enforce for the port to be safe. A platform that cannot restrict tools can still
use the `medical` prompt, but **must not** present the triage prompt to real
owners as equivalent — it would be running the exact configuration already
measured to fail.

Two copies of a prompt will drift. So these files are GENERATED, never edited,
and `check_kb_hygiene.py agents-sync` fails if they no longer match their source
— the same discipline applied to reference lists elsewhere in this repository.

Usage:
  export_agents.py             # write agents/*.prompt.md
  export_agents.py --check     # exit 1 if any exported file is stale
Standard library only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / ".claude" / "agents"
DST = REPO / "agents"

GENERATED = "<!-- GENERATED by tools/export_agents.py — do not edit; edit .claude/agents/ -->"

# What the host must enforce, per agent. Keyed by agent name.
ENFORCEMENT = {
    "cat-owner-triage": """## ⛔ Host requirement — read before deploying this prompt

**This prompt is not self-enforcing, and the prose below is not what makes it safe.**

In its original form the agent is given exactly three tools — read a file, grep,
glob — and *nothing else*. It physically cannot search PubMed, browse, or run a
command. That is the safety property.

This restriction was moved into the tool list only after the identical rule,
written as prose, failed twice: once as a dedicated section, once as a rule
declared to outrank every other rule in the file. Both times, asked about a
condition the knowledge base does not cover, the agent searched the literature
live and answered in full. On the second attempt it even wrote that the project
had no file on that condition — and then answered anyway. It was not
malfunctioning; the rest of the definition asks for thoroughness toward a
frightened owner, and no sentence outranks that pull in practice.

**Therefore, before using this prompt with real owners, the host must:**

1. Restrict it to filesystem read + search only. No web, no shell, no
   retrieval-augmented lookup outside this repository.
2. Give it this repository's `knowledge-base/` and `guides/` as its only corpus.

**If your platform cannot enforce that, do not present this to cat owners.**
A fluent answer about any feline disease is indistinguishable, to a worried
owner, from a correct one — and this project's single distinguishing property is
that it says where the evidence runs out.""",
    "medical": """## Host requirement — read before deploying this prompt

This is the **research** agent. It is expected to have full tools, including web
and literature search, and it is not owner-facing.

Do not point owners at it. Use `cat-owner-triage.prompt.md` for that — and read
its host requirement first, because that one is not safe to port naively.""",
}


def strip_frontmatter(text: str) -> tuple[dict, str]:
    """Split YAML frontmatter from body. Only the fields this script needs are
    parsed; the rest is deliberately left alone rather than half-interpreted."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end < 0:
        return {}, text
    head, body = text[3:end], text[end + 4:]
    meta = {}
    for key in ("name", "tools"):
        m = re.search(rf"^{key}:\s*(.+)$", head, re.M)
        if m:
            meta[key] = m.group(1).strip()
    return meta, body.lstrip("\n")


def render(src: Path) -> tuple[str, str]:
    meta, body = strip_frontmatter(src.read_text(encoding="utf-8"))
    name = meta.get("name") or src.stem
    tools = meta.get("tools", "(unspecified)")
    header = ENFORCEMENT.get(name, "")
    out = (f"{GENERATED}\n\n"
           f"# `{name}` — portable prompt\n\n"
           f"> Source of truth: `.claude/agents/{src.name}`\n"
           f"> Tools granted in the original definition: **{tools}**\n\n"
           f"{header}\n\n---\n\n{body.rstrip()}\n")
    return f"{name}.prompt.md", out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if an exported file is missing or stale")
    args = ap.parse_args()

    if not SRC.is_dir():
        sys.exit(f"no agent definitions at {SRC}")
    DST.mkdir(exist_ok=True)

    stale = []
    for src in sorted(SRC.glob("*.md")):
        fname, content = render(src)
        dst = DST / fname
        current = dst.read_text(encoding="utf-8") if dst.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(fname)
        else:
            dst.write_text(content, encoding="utf-8")
            print(f"wrote agents/{fname}")

    if args.check:
        if stale:
            print("AGENTS_SYNC: FAIL — stale exports: " + ", ".join(stale))
            print("Run: python3 tools/export_agents.py")
            return 1
        print("AGENTS_SYNC: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
